Repository 2024-pre-onboarding-backend-F/yellow-ribbon, pull requests merged in 2024-10, with the labels that each got.

#29 [feat] 데이터파이프라인 공공데이터 수집 기능 고도화
  build.gradle
  src/main/java/wanted/ribbon/datapipe/component/DataFetchTasklet.java
  src/main/java/wanted/ribbon/datapipe/component/DataPipeJobScheduler.java
  src/main/java/wanted/ribbon/datapipe/component/DataPipeTasklet.java
  src/main/java/wanted/ribbon/datapipe/config/AppConfig.java
  src/main/java/wanted/ribbon/datapipe/config/DataPipeJobConfig.java
  src/main/java/wanted/ribbon/datapipe/controller/OpenApiController.java
  src/main/java/wanted/ribbon/datapipe/domain/Genrestrt.java
  src/main/java/wanted/ribbon/datapipe/dto/GenrestrtApiResponse.java
  src/main/java/wanted/ribbon/datapipe/dto/GyeongGiList.java
  src/main/java/wanted/ribbon/datapipe/dto/RawData.java
  src/main/java/wanted/ribbon/datapipe/mapper/RawDataRowMapper.java
  src/main/java/wanted/ribbon/datapipe/mapper/StoreDataRowMapper.java
  src/main/java/wanted/ribbon/datapipe/repository/GenrestrtRepository.java
  src/main/java/wanted/ribbon/datapipe/service/DataProcessor.java
  src/main/java/wanted/ribbon/datapipe/service/GenrestrtService.java
  src/main/java/wanted/ribbon/datapipe/service/RawDataService.java
  src/main/java/wanted/ribbon/genrestrt/config/AppConfig.java
  src/main/java/wanted/ribbon/genrestrt/controller/GenrestrtController.java
  src/main/java/wanted/ribbon/user/config/WebSecurityConfig.java
Labels: feat, refactor

#31 swagger 설정 기능 구현
  build.gradle
  src/main/java/wanted/ribbon/datapipe/controller/OpenApiController.java
  src/main/java/wanted/ribbon/global/config/SwaggerConfig.java
  src/main/java/wanted/ribbon/user/config/WebSecurityConfig.java
Labels: feat

#33 [feat] 인기 맛집 조회 기능 구현
  build.gradle
  src/main/java/wanted/ribbon/RibbonApplication.java
  src/main/java/wanted/ribbon/global/config/RedisConfig.java
  src/main/java/wanted/ribbon/store/controller/StoreController.java
  src/main/java/wanted/ribbon/store/domain/Store.java
  src/main/java/wanted/ribbon/store/dto/PopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/repository/StoreRepository.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
  src/main/resources/application.yml
Labels: feat

#36 [feat] 인기 급상승 맛집 조회 기능 구현
  src/main/java/wanted/ribbon/RibbonApplication.java
  src/main/java/wanted/ribbon/global/config/RedisConfig.java
  src/main/java/wanted/ribbon/store/controller/StoreController.java
  src/main/java/wanted/ribbon/store/domain/Review.java
  src/main/java/wanted/ribbon/store/domain/Store.java
  src/main/java/wanted/ribbon/store/dto/RisingPopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/RisingStoreResponseDto.java
  src/main/java/wanted/ribbon/store/repository/ReviewRepository.java
  src/main/java/wanted/ribbon/store/service/ReviewService.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
Labels: feat

#38 [refactor] 맛집 목록 조회 기능 개선 (공간 데이터 베이스 적용)
  build.gradle
  src/main/java/wanted/ribbon/store/domain/Store.java
  src/main/java/wanted/ribbon/store/dto/StoreListResponseDto.java
  src/main/java/wanted/ribbon/store/repository/StoreRepository.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
  src/main/resources/application.yml
Labels: feat, refactor

#41 [fix] 공간 데이터 베이스 적용 후 발생한 버그 해결
  src/main/java/wanted/ribbon/datapipe/component/DataPipeTasklet.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
  src/main/resources/application.yml
Labels: bug

#43 [feat] DockerFile을 활용한 배포
  Dockerfile
  build.gradle
  gradlew
  src/main/java/wanted/ribbon/store/service/StoreService.java
Labels: feat

#44 [merge] dev2 브랜치 main으로 merge
  Dockerfile
  build.gradle
  gradlew
  src/main/java/wanted/ribbon/RibbonApplication.java
  src/main/java/wanted/ribbon/datapipe/component/DataFetchTasklet.java
  src/main/java/wanted/ribbon/datapipe/component/DataPipeJobScheduler.java
  src/main/java/wanted/ribbon/datapipe/component/DataPipeTasklet.java
  src/main/java/wanted/ribbon/datapipe/component/JobCompletionNotificationListener.java
  src/main/java/wanted/ribbon/datapipe/config/AppConfig.java
  src/main/java/wanted/ribbon/datapipe/config/BatchConfig.java
  src/main/java/wanted/ribbon/datapipe/config/DataPipeJobConfig.java
  src/main/java/wanted/ribbon/datapipe/config/OpenApiJobConfig.java
  src/main/java/wanted/ribbon/datapipe/controller/OpenApiController.java
  src/main/java/wanted/ribbon/datapipe/domain/Genrestrt.java
  src/main/java/wanted/ribbon/datapipe/dto/GenrestrtApiResponse.java
  src/main/java/wanted/ribbon/datapipe/dto/GyeongGiList.java
  src/main/java/wanted/ribbon/datapipe/dto/RawData.java
  src/main/java/wanted/ribbon/datapipe/mapper/RawDataRowMapper.java
  src/main/java/wanted/ribbon/datapipe/mapper/StoreDataRowMapper.java
  src/main/java/wanted/ribbon/datapipe/repository/GenrestrtRepository.java
  src/main/java/wanted/ribbon/datapipe/service/DataProcessor.java
  src/main/java/wanted/ribbon/datapipe/service/GenrestrtService.java
  src/main/java/wanted/ribbon/datapipe/service/RawDataSaveService.java
  src/main/java/wanted/ribbon/datapipe/service/RawDataService.java
  src/main/java/wanted/ribbon/genrestrt/component/DataPipeJobScheduler.java
  src/main/java/wanted/ribbon/genrestrt/config/AppConfig.java
  src/main/java/wanted/ribbon/genrestrt/controller/GenrestrtController.java
  src/main/java/wanted/ribbon/genrestrt/repository/GenrestrtRepository.java
  src/main/java/wanted/ribbon/genrestrt/service/DataProcessor.java
  src/main/java/wanted/ribbon/global/config/RedisConfig.java
  src/main/java/wanted/ribbon/global/config/SwaggerConfig.java
  src/main/java/wanted/ribbon/store/controller/StoreController.java
  src/main/java/wanted/ribbon/store/domain/Category.java
  src/main/java/wanted/ribbon/store/domain/Review.java
  src/main/java/wanted/ribbon/store/domain/Store.java
  src/main/java/wanted/ribbon/store/dto/PopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/RisingPopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/RisingStoreResponseDto.java
  src/main/java/wanted/ribbon/store/dto/StoreListResponseDto.java
  src/main/java/wanted/ribbon/store/repository/ReviewRepository.java
  src/main/java/wanted/ribbon/store/repository/StoreRepository.java
  src/main/java/wanted/ribbon/store/service/ReviewService.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
  src/main/java/wanted/ribbon/user/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: bug, feat, refactor, merge

#46 [fix] genrestrts 테이블의 경도(lon)와 위도(lat) 데이터가 반대로 저장된 문제 해결
  src/main/java/wanted/ribbon/datapipe/component/DataPipeTasklet.java
  src/main/java/wanted/ribbon/datapipe/dto/GyeongGiList.java
  src/main/java/wanted/ribbon/store/controller/StoreController.java
  src/main/java/wanted/ribbon/store/domain/Store.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
Labels: bug

#49 [refactor] Swagger API 문서 작성
  src/main/java/wanted/ribbon/store/controller/CityController.java
  src/main/java/wanted/ribbon/store/controller/ReviewController.java
  src/main/java/wanted/ribbon/store/controller/StoreController.java
  src/main/java/wanted/ribbon/store/dto/CityResponseDto.java
  src/main/java/wanted/ribbon/store/dto/CreateReviewRequestDto.java
  src/main/java/wanted/ribbon/store/dto/CreateReviewResponseDto.java
  src/main/java/wanted/ribbon/store/dto/PopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/ReviewListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/RisingPopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/RisingStoreResponseDto.java
  src/main/java/wanted/ribbon/store/dto/StoreDetailResponseDto.java
Labels: refactor

#50 [feat] 카카오 로그인 기능 추가
  build.gradle
  src/main/java/wanted/ribbon/global/response/ResponseCode.java
  src/main/java/wanted/ribbon/global/response/ResponseDto.java
  src/main/java/wanted/ribbon/user/config/WebSecurityConfig.java
  src/main/java/wanted/ribbon/user/controller/UserApiController.java
  src/main/java/wanted/ribbon/user/controller/UserOauthController.java
  src/main/java/wanted/ribbon/user/domain/RefreshToken.java
  src/main/java/wanted/ribbon/user/domain/SocialType.java
  src/main/java/wanted/ribbon/user/domain/User.java
  src/main/java/wanted/ribbon/user/dto/LoginRequestDto.java
  src/main/java/wanted/ribbon/user/dto/LoginResponseDto.java
  src/main/java/wanted/ribbon/user/dto/SignUpUserRequest.java
  src/main/java/wanted/ribbon/user/repository/UserRepository.java
  src/main/java/wanted/ribbon/user/service/CustomUserDetail.java
  src/main/java/wanted/ribbon/user/service/KakaoOAuth2UserService.java
  src/main/java/wanted/ribbon/user/service/UserDetailService.java
  src/main/java/wanted/ribbon/user/service/UserOauthService.java
  src/main/java/wanted/ribbon/user/service/UserService.java
  src/test/java/wanted/ribbon/user/config/jwt/JwtFactory.java
Labels: feat

#52 [feat] 사용자 위치 기반 맛집 추천 기능 구현
  src/main/java/wanted/ribbon/store/controller/StoreController.java
  src/main/java/wanted/ribbon/store/dto/StoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/StoreResponseDto.java
  src/main/java/wanted/ribbon/store/repository/StoreRepository.java
  src/main/java/wanted/ribbon/store/repository/StoreRepositoryCustom.java
  src/main/java/wanted/ribbon/store/repository/StoreRepositoryImpl.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
Labels: feat

#53 [refactor] 사용자 Swagger API 문서 추가
  build.gradle
  src/main/java/wanted/ribbon/user/controller/TokenApiController.java
  src/main/java/wanted/ribbon/user/controller/UserApiController.java
  src/main/java/wanted/ribbon/user/controller/UserOauthController.java
  src/main/java/wanted/ribbon/user/dto/CreateAccessTokenRequest.java
  src/main/java/wanted/ribbon/user/dto/CreateAccessTokenResponse.java
  src/main/java/wanted/ribbon/user/dto/CreateRefreshTokenRequest.java
  src/main/java/wanted/ribbon/user/dto/LoginRequest.java
  src/main/java/wanted/ribbon/user/dto/LoginRequestDto.java
  src/main/java/wanted/ribbon/user/dto/LoginResponse.java
  src/main/java/wanted/ribbon/user/dto/LoginResponseDto.java
  src/main/java/wanted/ribbon/user/dto/ProfileRequest.java
  src/main/java/wanted/ribbon/user/dto/ProfileResponse.java
  src/main/java/wanted/ribbon/user/dto/SignUpRequest.java
  src/main/java/wanted/ribbon/user/dto/SignUpResponse.java
  src/main/java/wanted/ribbon/user/dto/SignUpUserRequest.java
  src/main/java/wanted/ribbon/user/dto/UpdateProfileRequest.java
  src/main/java/wanted/ribbon/user/dto/UpdateProfileResponse.java
  src/main/java/wanted/ribbon/user/dto/UpdateUserRequest.java
  src/main/java/wanted/ribbon/user/dto/UpdateUserResponse.java
  src/main/java/wanted/ribbon/user/service/KakaoOAuth2UserService.java
  src/main/java/wanted/ribbon/user/service/UserOauthService.java
  src/main/java/wanted/ribbon/user/service/UserService.java
Labels: refactor

#54 [merge] dev2 브랜치 main으로 merge
  build.gradle
  src/main/java/wanted/ribbon/datapipe/component/DataPipeTasklet.java
  src/main/java/wanted/ribbon/datapipe/dto/GyeongGiList.java
  src/main/java/wanted/ribbon/global/response/ResponseCode.java
  src/main/java/wanted/ribbon/global/response/ResponseDto.java
  src/main/java/wanted/ribbon/store/controller/CityController.java
  src/main/java/wanted/ribbon/store/controller/ReviewController.java
  src/main/java/wanted/ribbon/store/controller/StoreController.java
  src/main/java/wanted/ribbon/store/domain/Store.java
  src/main/java/wanted/ribbon/store/dto/CityResponseDto.java
  src/main/java/wanted/ribbon/store/dto/CreateReviewRequestDto.java
  src/main/java/wanted/ribbon/store/dto/CreateReviewResponseDto.java
  src/main/java/wanted/ribbon/store/dto/PopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/ReviewListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/RisingPopularStoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/RisingStoreResponseDto.java
  src/main/java/wanted/ribbon/store/dto/StoreDetailResponseDto.java
  src/main/java/wanted/ribbon/store/dto/StoreListResponseDto.java
  src/main/java/wanted/ribbon/store/dto/StoreResponseDto.java
  src/main/java/wanted/ribbon/store/repository/StoreRepository.java
  src/main/java/wanted/ribbon/store/repository/StoreRepositoryCustom.java
  src/main/java/wanted/ribbon/store/repository/StoreRepositoryImpl.java
  src/main/java/wanted/ribbon/store/service/StoreService.java
  src/main/java/wanted/ribbon/user/config/WebSecurityConfig.java
  src/main/java/wanted/ribbon/user/controller/TokenApiController.java
  src/main/java/wanted/ribbon/user/controller/UserApiController.java
  src/main/java/wanted/ribbon/user/controller/UserOauthController.java
  src/main/java/wanted/ribbon/user/domain/RefreshToken.java
  src/main/java/wanted/ribbon/user/domain/SocialType.java
  src/main/java/wanted/ribbon/user/domain/User.java
  src/main/java/wanted/ribbon/user/dto/CreateAccessTokenRequest.java
  src/main/java/wanted/ribbon/user/dto/CreateAccessTokenResponse.java
  src/main/java/wanted/ribbon/user/dto/CreateRefreshTokenRequest.java
  src/main/java/wanted/ribbon/user/dto/LoginRequest.java
  src/main/java/wanted/ribbon/user/dto/LoginResponse.java
  src/main/java/wanted/ribbon/user/dto/ProfileRequest.java
  src/main/java/wanted/ribbon/user/dto/ProfileResponse.java
  src/main/java/wanted/ribbon/user/dto/SignUpRequest.java
  src/main/java/wanted/ribbon/user/dto/SignUpResponse.java
  src/main/java/wanted/ribbon/user/dto/SignUpUserRequest.java
  src/main/java/wanted/ribbon/user/dto/UpdateProfileRequest.java
  src/main/java/wanted/ribbon/user/dto/UpdateProfileResponse.java
  src/main/java/wanted/ribbon/user/dto/UpdateUserRequest.java
  src/main/java/wanted/ribbon/user/dto/UpdateUserResponse.java
  src/main/java/wanted/ribbon/user/dto/UserLoginRequestDto.java
  src/main/java/wanted/ribbon/user/dto/UserLoginResponseDto.java
  src/main/java/wanted/ribbon/user/repository/UserRepository.java
  src/main/java/wanted/ribbon/user/service/CustomUserDetail.java
  src/main/java/wanted/ribbon/user/service/KakaoOAuth2UserService.java
  src/main/java/wanted/ribbon/user/service/UserDetailService.java
  src/main/java/wanted/ribbon/user/service/UserOauthService.java
  src/main/java/wanted/ribbon/user/service/UserService.java
  src/test/java/wanted/ribbon/user/config/jwt/JwtFactory.java
Labels: bug, feat, refactor, merge

#55 fix : User 매핑
  src/main/java/wanted/ribbon/store/service/ReviewService.java
Labels: bug

#56 [fix] : 의존성 수정
  src/main/resources/application.yml
Labels: bug
